#!/usr/bin/env python3
#
# Copyright (C) 2016 James Murphy
# Licensed under the GPL version 2 only
#
# A battery indicator blocklet script for i3blocks

from subprocess import check_output
import os
import re

config = dict(os.environ)
devices = check_output(['upower', '-e'], universal_newlines=True).split('\n')
for device in devices:
    if 'battery_BAT' in device:
        break


status = check_output(['upower', '-i', device], universal_newlines=True).split('\n')
for line in status:
    if 'percentage' in line:
        percent = int(line.split(':')[1].strip()[0:-1])
    if 'state' in line:
        state = line.split(':')[1].strip()
    if 'time to full' in line:
        time_to_full = line.split(':')[1].strip()
    if 'time to empty' in line:
        time_to_empty = line.split(':')[1].strip()

if state == 'discharging':
    time_left = ' ' + time_to_empty
elif state == 'charging':
    time_left = ' ' + time_to_full
else:
    time_left = ''

def color(percent):
    if percent < 10:
        return "#FF4040"
    if percent < 20:
        return "#FF673D"
    if percent < 30:
        return "#FFB429"
    if percent < 40:
        return "#FFD954"
    if percent < 50:
        return "#FFF861"
    if percent < 60:
        return "#DCFF6C"
    if percent < 70:
        return "#CAFF6C"
    if percent < 80:
        return "#B4FF6C"
    if percent < 90:
        return "#93FF6C"
    return "#47FF6C"

def battery_icon(percent):
    if state == "discharging":
        if percent < 10:
            return "󰁺"
        elif percent < 20:
            return "󰁻"
        elif percent < 30:
            return "󰁼"
        elif percent < 40:
            return "󰁽"
        elif percent < 50:
            return "󰁾"
        elif percent < 60:
            return "󰁿"
        elif percent < 70:
            return "󰂀"
        elif percent < 80:
            return "󰂁"
        elif percent < 90:
            return "󰂂"
        else:
            return "󰁹"
    else:
        return ""

fulltext =  f'<span color="{color(percent)}">{battery_icon(percent)} {percent}%</span>'
fulltext += time_left

print(fulltext)
if percent < 10:
    exit(33)