#!/usr/bin/python

import subprocess
import re
import fileinput
import json
import os


def defaultSinkName():
    return (
        subprocess.run(["pactl", "get-default-sink"], capture_output=True)
        .stdout.decode()
        .strip()
    )


def allSinks():
    tmp = (
        subprocess.run(["pactl", "list", "short", "sinks"], capture_output=True)
        .stdout.decode()
        .strip()
        .split("\n")
    )
    sinks = []
    for sink in tmp:
        a = sink.split("\t")
        if "hdmi" in a[1]:
            continue
        sinks.append((a[0], a[1]))
    return sinks


def print_status():
    volume = (
        subprocess.run(
            ["pactl", "get-sink-volume", "@DEFAULT_SINK@"], capture_output=True
        )
        .stdout.decode()
        .strip()
    )
    volume = re.search("[0-9]+%", volume).group(0)

    mute = (
        subprocess.run(
            ["pactl", "get-sink-mute", "@DEFAULT_SINK@"], capture_output=True
        )
        .stdout.decode()
        .strip()
    )
    mute = "yes" in mute

    defaultName = defaultSinkName()
    nameMap = {
        "alsa_output.pci-0000_0a_00.4.analog-stereo": "🔊 Speakers",
        "bluez_output.0C_AE_BD_06_99_5A.1": "󰓃 Edifiers",
        "alsa_output.pci-0000_c1_00.6.analog-stereo": " Internals",
        "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo": "🎧 Headphones",
    }
    name = nameMap.get(defaultName) or defaultName

    volume = volume if not mute else "🔇"
    print(f"{name} {volume}")


def next_sink():
    sinks = allSinks()
    nextSinkIndex = 0
    for i, sink in enumerate(sinks):
        if sink[1] == defaultSinkName():
            nextSinkIndex = i
            break
    else:
        print("error")
        exit

    nextSink = sinks[(nextSinkIndex + 1) % len(sinks)]

    defaultSink = (
        subprocess.run(["pactl", "set-default-sink", nextSink[0]], capture_output=True)
        .stdout.decode()
        .strip()
    )


if __name__ == "__main__":
    if os.getenv("button") == "1":
        next_sink()
    if os.getenv("button") == "4":
        subprocess.run(["amixer", "-q", "-D", "pulse", "sset", "Master", "2%+"])
    if os.getenv("button") == "5":
        subprocess.run(["amixer", "-q", "-D", "pulse", "sset", "Master", "2%-"])
    print_status()
