# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Setup for oh-my-zsh
export ZSH="/home/luc/.oh-my-zsh"

plugins=(git)

source $ZSH/oh-my-zsh.sh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Extend PATH

export PATH=$PATH:~/.cargo/bin/
export RUSTC_WRAPPER=/home/luc/.cargo/bin/sccache
export PATH=$PATH:/opt/resolve/bin

NPM_PACKAGES="${HOME}/.npm-packages"

export PATH="$PATH:$NPM_PACKAGES/bin"

# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

# Setup atuin (command history manager)
eval "$(atuin init --disable-up-arrow zsh)"

# Setup pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/luc/.lmstudio/bin"

# Setup pnpm
export PNPM_HOME="/home/luc/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

{{#if dotter.packages.oh-my-posh}}
# Setup oh-my-posh (terminal prompt)
eval "$(oh-my-posh -c ~/.oh-my-posh.yaml init zsh)"
{{/if}}

{{#if dotter.packages.starship}}
# Setup starship (terminal prompt)
eval "$(starship init zsh)"
{{/if}}
